export const sectorData = [
    { id: "command-center", name: "Centro de Mando", status: "Nominal", color: "bg-green-500" },
    { id: "residential", name: "Módulos Residenciales", status: "Nominal", color: "bg-green-500" },
    { id: "science-lab", name: "Laboratorio Científico", status: "Activo", color: "bg-blue-500" },
    { id: "greenhouses", name: "Invernaderos", status: "Nominal", color: "bg-green-500" },
    { id: "eclss", name: "Soporte Vital (ECLSS)", status: "Nominal", color: "bg-green-500" },
    { id: "storage", name: "Almacenamiento", status: "En Espera", color: "bg-yellow-500" },
];

export const crewData = [
  { id: 'cmdr-alex', name: 'Cmdr. Alex Reyes', role: 'Comandante de Misión', vitals: { hr: 68, spo2: 99, temp: 36.8 }, sector: 'command-center' },
  { id: 'dr-lena', name: 'Dra. Lena Petrova', role: 'Oficial Científico', vitals: { hr: 72, spo2: 98, temp: 37.0 }, sector: 'science-lab' },
  { id: 'ken-sato', name: 'Ken Sato', role: 'Ingeniero de Sistemas', vitals: { hr: 75, spo2: 99, temp: 36.9 }, sector: 'eclss' },
  { id: 'maya-singh', name: 'Maya Singh', role: 'Especialista de Hábitat', vitals: { hr: 65, spo2: 100, temp: 36.7 }, sector: 'greenhouses' },
  { id: 'javier-rodriguez', name: 'Javier Rodriguez', role: 'Geólogo', vitals: { hr: 70, spo2: 98, temp: 36.9 }, sector: 'science-lab' },
  { id: 'chen-liang', name: 'Chen Liang', role: 'Médico', vitals: { hr: 66, spo2: 99, temp: 36.8 }, sector: 'residential' },
  { id: 'olivia-garcia', name: 'Olivia Garcia', role: 'Técnico de Robótica', vitals: { hr: 78, spo2: 97, temp: 37.1 }, sector: 'eclss' },
  { id: 'ben-carter', name: 'Ben Carter', role: 'Piloto', vitals: { hr: 71, spo2: 99, temp: 36.9 }, sector: 'command-center' },
  { id: 'fatima-al-sayed', name: 'Fatima Al-Sayed', role: 'Botánica', vitals: { hr: 69, spo2: 99, temp: 36.7 }, sector: 'greenhouses' },
  { id: 'ivan-dubov', name: 'Ivan Dubov', role: 'Ingeniero Estructural', vitals: { hr: 73, spo2: 98, temp: 37.0 }, sector: 'storage' },
  { id: 'sophia-rossi', name: 'Sophia Rossi', role: 'Psicóloga', vitals: { hr: 67, spo2: 100, temp: 36.8 }, sector: 'residential' },
  { id: 'leo-schmidt', name: 'Leo Schmidt', role: 'Técnico de Comunicaciones', vitals: { hr: 74, spo2: 99, temp: 37.0 }, sector: 'command-center' },
  { id: 'emily-white', name: 'Emily White', role: 'Astrobióloga', vitals: { hr: 70, spo2: 98, temp: 36.9 }, sector: 'science-lab' },
  { id: 'david-chen', name: 'David Chen', role: 'Técnico de Soporte Vital', vitals: { hr: 76, spo2: 99, temp: 37.1 }, sector: 'eclss' },
  { id: 'chloe-kim', name: 'Chloe Kim', role: 'Nutricionista', vitals: { hr: 68, spo2: 100, temp: 36.7 }, sector: 'greenhouses' },
  { id: 'omar-badawi', name: 'Omar Badawi', role: 'Ingeniero de Software', vitals: { hr: 72, spo2: 98, temp: 36.9 }, sector: 'command-center' },
  { id: 'ana-silva', name: 'Ana Silva', role: 'Paramédico', vitals: { hr: 69, spo2: 99, temp: 36.8 }, sector: 'residential' },
  { id: 'daniel-jones', name: 'Daniel Jones', role: 'Técnico de Mantenimiento', vitals: { hr: 79, spo2: 97, temp: 37.2 }, sector: 'storage' },
  { id: 'sara-nilsson', name: 'Sara Nilsson', role: 'Investigadora', vitals: { hr: 71, spo2: 98, temp: 36.9 }, sector: 'science-lab' },
  { id: 'wei-zhang', name: 'Wei Zhang', role: 'Especialista Agrónomo', vitals: { hr: 66, spo2: 100, temp: 36.6 }, sector: 'greenhouses' },
];

export const sectorAnalysisData = {
  "command-center": {
    name: "Centro de Mando (A)",
    status: {
      label: "Nominal",
      color: "text-green-400",
      bgColor: "bg-green-400/10",
    },
    activityLevel: 85,
    crewCondition: 92,
    energy: {
      consumption: 12.5,
      capacity: 15,
      internalSourcePct: 78,
      systemTemp: 45,
      thermalEfficiency: 99.1,
      alerts: [],
    },
    environment: {
      lighting: 450,
      emergencyLights: "OK",
      temperature: 21.5,
      airQuality: 99.8,
      co2: 410,
      noise: 40,
    },
    infrastructure: {
      integrity: 99.9,
      vibrations: "None",
      maintenance: [],
      lifeSupport: "Nominal",
    },
    events: [
      { id: 1, type: "info", text: "J. Rodriguez ingresó al sector.", time: "hace 2m" },
      { id: 2, type: "info", text: "Sistema de navegación activado.", time: "hace 5m" },
      { id: 3, type: "system", text: "Calibración de antena completada.", time: "hace 15m" },
    ],
    crew: {
      assigned: 5,
      status: "Activo",
      occupation: 100,
      comfort: 4.8,
    },
  },
  "science-lab": {
    name: "Laboratorio Científico (B)",
    status: {
      label: "En Revisión",
      color: "text-yellow-400",
      bgColor: "bg-yellow-400/10",
    },
    activityLevel: 60,
    crewCondition: 88,
    energy: {
      consumption: 18.2,
      capacity: 20,
      internalSourcePct: 65,
      systemTemp: 52,
      thermalEfficiency: 98.5,
      alerts: ["Pico de consumo en espectrómetro"],
    },
    environment: {
      lighting: 600,
      emergencyLights: "OK",
      temperature: 20.1,
      airQuality: 99.5,
      co2: 450,
      noise: 55,
    },
    infrastructure: {
      integrity: 99.7,
      vibrations: "Low",
      maintenance: ["Calibrar sensor de gases #3"],
      lifeSupport: "Nominal",
    },
    events: [
        { id: 1, type: "warning", text: "Pico de consumo detectado en espectrómetro.", time: "hace 1m" },
        { id: 2, type: "info", text: "Análisis de muestra #A-34 iniciado.", time: "hace 8m" },
        { id: 3, type: "info", text: "Dr. Petrova ingresó al sector.", time: "hace 12m" },
    ],
    crew: {
      assigned: 4,
      status: "Activo",
      occupation: 75,
      comfort: 4.5,
    },
  },
  "residential": {
    name: "Módulos Residenciales (C)",
    status: {
      label: "Nominal",
      color: "text-green-400",
      bgColor: "bg-green-400/10",
    },
    activityLevel: 40,
    crewCondition: 95,
    energy: {
      consumption: 8,
      capacity: 10,
      internalSourcePct: 90,
      systemTemp: 40,
      thermalEfficiency: 99.5,
      alerts: [],
    },
    environment: {
      lighting: 250,
      emergencyLights: "OK",
      temperature: 22,
      airQuality: 99.9,
      co2: 380,
      noise: 30,
    },
    infrastructure: {
      integrity: 99.9,
      vibrations: "None",
      maintenance: [],
      lifeSupport: "Nominal",
    },
    events: [
      { id: 1, type: "info", text: "Ciclo de sueño iniciado para la mayoría de la tripulación.", time: "hace 2h" },
    ],
    crew: {
      assigned: 11,
      status: "Descanso",
      occupation: 50,
      comfort: 4.9,
    },
  },
  "greenhouses": {
    name: "Invernaderos (D)",
    status: {
      label: "Nominal",
      color: "text-green-400",
      bgColor: "bg-green-400/10",
    },
    activityLevel: 75,
    crewCondition: 90,
    energy: {
      consumption: 15,
      capacity: 18,
      internalSourcePct: 85,
      systemTemp: 48,
      thermalEfficiency: 99.2,
      alerts: [],
    },
    environment: {
      lighting: 1000,
      emergencyLights: "OK",
      temperature: 24,
      airQuality: 99.7,
      co2: 600,
      noise: 45,
    },
    infrastructure: {
      integrity: 99.8,
      vibrations: "None",
      maintenance: [],
      lifeSupport: "Nominal",
    },
    events: [
        { id: 1, type: "system", text: "Ciclo de riego automático completado.", time: "hace 30m" },
    ],
    crew: {
      assigned: 4,
      status: "Activo",
      occupation: 100,
      comfort: 4.7,
    },
  },
  "eclss": {
    name: "Soporte Vital (E)",
    status: {
      label: "Crítico",
      color: "text-red-400",
      bgColor: "bg-red-400/10",
    },
    activityLevel: 95,
    crewCondition: 85,
    energy: {
      consumption: 25,
      capacity: 25,
      internalSourcePct: 50,
      systemTemp: 65,
      thermalEfficiency: 97,
      alerts: ["Fallo en el reciclador de agua #2"],
    },
    environment: {
      lighting: 500,
      emergencyLights: "OK",
      temperature: 23,
      airQuality: 98,
      co2: 500,
      noise: 65,
    },
    infrastructure: {
      integrity: 99,
      vibrations: "High",
      maintenance: ["Revisar reciclador de agua #2"],
      lifeSupport: "Alerta",
    },
    events: [
        { id: 1, type: "warning", text: "Fallo en el reciclador de agua #2. Sistema de respaldo activado.", time: "hace 5m" },
    ],
    crew: {
      assigned: 3,
      status: "Activo",
      occupation: 100,
      comfort: 3.5,
    },
  },
  "storage": {
    name: "Almacenamiento (F)",
    status: {
      label: "En Espera",
      color: "text-yellow-400",
      bgColor: "bg-yellow-400/10",
    },
    activityLevel: 10,
    crewCondition: 98,
    energy: {
      consumption: 2,
      capacity: 5,
      internalSourcePct: 100,
      systemTemp: 35,
      thermalEfficiency: 99.8,
      alerts: [],
    },
    environment: {
      lighting: 100,
      emergencyLights: "OK",
      temperature: 18,
      airQuality: 99.9,
      co2: 400,
      noise: 25,
    },
    infrastructure: {
      integrity: 100,
      vibrations: "None",
      maintenance: [],
      lifeSupport: "Nominal",
    },
    events: [
        { id: 1, type: "info", text: "Sector en modo de bajo consumo.", time: "hace 8h" },
    ],
    crew: {
      assigned: 2,
      status: "Descanso",
      occupation: 10,
      comfort: 4.6,
    },
  },
};
