
type Translator = (key: string) => string;

export const getSectorData = (t: Translator) => [
    { id: "command-center", name: t('analysis.sector_command-center_name'), status: t('dashboard.sector_nominal'), color: "bg-green-500" },
    { id: "residential", name: t('analysis.sector_residential_name'), status: t('dashboard.sector_nominal'), color: "bg-green-500" },
    { id: "science-lab", name: t('analysis.sector_science-lab_name'), status: t('dashboard.sector_active'), color: "bg-blue-500" },
    { id: "greenhouses", name: t('analysis.sector_greenhouses_name'), status: t('dashboard.sector_nominal'), color: "bg-green-500" },
    { id: "eclss", name: t('analysis.sector_eclss_name'), status: t('dashboard.sector_nominal'), color: "bg-green-500" },
    { id: "storage", name: t('analysis.sector_storage_name'), status: t('dashboard.sector_standby'), color: "bg-yellow-500" },
];

export const getCrewData = (t: Translator) => [
  { id: 'cmdr-alex', name: 'Cmdr. Alex Reyes', role: t('oshi.commander'), vitals: { hr: 68, spo2: 99, temp: 36.8 }, sector: 'command-center' },
  { id: 'dr-lena', name: 'Dra. Lena Petrova', role: t('oshi.science_officer'), vitals: { hr: 72, spo2: 98, temp: 37.0 }, sector: 'science-lab' },
  { id: 'ken-sato', name: 'Ken Sato', role: t('oshi.systems_engineer'), vitals: { hr: 75, spo2: 99, temp: 36.9 }, sector: 'eclss' },
  { id: 'maya-singh', name: 'Maya Singh', role: t('oshi.habitat_specialist'), vitals: { hr: 65, spo2: 100, temp: 36.7 }, sector: 'greenhouses' },
  { id: 'javier-rodriguez', name: 'Javier Rodriguez', role: t('oshi.geologist'), vitals: { hr: 70, spo2: 98, temp: 36.9 }, sector: 'science-lab' },
  { id: 'chen-liang', name: 'Chen Liang', role: t('oshi.doctor'), vitals: { hr: 66, spo2: 99, temp: 36.8 }, sector: 'residential' },
  { id: 'olivia-garcia', name: 'Olivia Garcia', role: t('oshi.robotics_technician'), vitals: { hr: 78, spo2: 97, temp: 37.1 }, sector: 'eclss' },
  { id: 'ben-carter', name: 'Ben Carter', role: t('oshi.pilot'), vitals: { hr: 71, spo2: 99, temp: 36.9 }, sector: 'command-center' },
  { id: 'fatima-al-sayed', name: 'Fatima Al-Sayed', role: t('oshi.botanist'), vitals: { hr: 69, spo2: 99, temp: 36.7 }, sector: 'greenhouses' },
  { id: 'ivan-dubov', name: 'Ivan Dubov', role: t('oshi.structural_engineer'), vitals: { hr: 73, spo2: 98, temp: 37.0 }, sector: 'storage' },
  { id: 'sophia-rossi', name: 'Sophia Rossi', role: t('oshi.psychologist'), vitals: { hr: 67, spo2: 100, temp: 36.8 }, sector: 'residential' },
  { id: 'leo-schmidt', name: 'Leo Schmidt', role: t('oshi.comms_technician'), vitals: { hr: 74, spo2: 99, temp: 37.0 }, sector: 'command-center' },
  { id: 'emily-white', name: 'Emily White', role: t('oshi.astrobiologist'), vitals: { hr: 70, spo2: 98, temp: 36.9 }, sector: 'science-lab' },
  { id: 'david-chen', name: 'David Chen', role: t('oshi.life_support_technician'), vitals: { hr: 76, spo2: 99, temp: 37.1 }, sector: 'eclss' },
  { id: 'chloe-kim', name: 'Chloe Kim', role: t('oshi.nutritionist'), vitals: { hr: 68, spo2: 100, temp: 36.7 }, sector: 'greenhouses' },
  { id: 'omar-badawi', name: 'Omar Badawi', role: t('oshi.software_engineer'), vitals: { hr: 72, spo2: 98, temp: 36.9 }, sector: 'command-center' },
  { id: 'ana-silva', name: 'Ana Silva', role: t('oshi.paramedic'), vitals: { hr: 69, spo2: 99, temp: 36.8 }, sector: 'residential' },
  { id: 'daniel-jones', name: 'Daniel Jones', role: t('oshi.maintenance_technician'), vitals: { hr: 79, spo2: 97, temp: 37.2 }, sector: 'storage' },
  { id: 'sara-nilsson', name: 'Sara Nilsson', role: t('oshi.researcher'), vitals: { hr: 71, spo2: 98, temp: 36.9 }, sector: 'science-lab' },
  { id: 'wei-zhang', name: 'Wei Zhang', role: t('oshi.agronomy_specialist'), vitals: { hr: 66, spo2: 100, temp: 36.6 }, sector: 'greenhouses' },
];

type TranslatorAnalysis = (key: string, args?: { [key: string]: string | number }) => string;

export const getSectorAnalysisData = (t: TranslatorAnalysis) => ({
  "command-center": {
    name: t('analysis.sector_command-center_name'),
    status: {
      label: t('analysis.status_nominal'),
      color: "text-green-400",
      bgColor: "bg-green-400/10",
    },
    activityLevel: 85,
    crewCondition: 92,
    energy: {
      consumption: 12.5,
      capacity: 15,
      internalSourcePct: 78,
      systemTemp: 45,
      thermalEfficiency: 99.1,
      alerts: [],
    },
    environment: {
      lighting: 450,
      emergencyLights: "OK",
      temperature: 21.5,
      airQuality: 99.8,
      co2: 410,
      noise: 40,
    },
    infrastructure: {
      integrity: 99.9,
      vibrations: t('analysis.vibrations_none'),
      maintenance: [],
      lifeSupport: t('analysis.status_nominal'),
    },
    events: [
      { id: 1, type: "info", text: t('analysis.event_cm_1'), time: t('analysis.time_2m') },
      { id: 2, type: "info", text: t('analysis.event_cm_2'), time: t('analysis.time_5m') },
      { id: 3, type: "system", text: t('analysis.event_cm_3'), time: t('analysis.time_15m') },
    ],
    crew: {
      assigned: 5,
      status: t('dashboard.sector_active'),
      occupation: 100,
      comfort: 4.8,
    },
  },
  "science-lab": {
    name: t('analysis.sector_science-lab_name'),
    status: {
      label: t('analysis.status_review'),
      color: "text-yellow-400",
      bgColor: "bg-yellow-400/10",
    },
    activityLevel: 60,
    crewCondition: 88,
    energy: {
      consumption: 18.2,
      capacity: 20,
      internalSourcePct: 65,
      systemTemp: 52,
      thermalEfficiency: 98.5,
      alerts: [t('analysis.alert_sl_1')],
    },
    environment: {
      lighting: 600,
      emergencyLights: "OK",
      temperature: 20.1,
      airQuality: 99.5,
      co2: 450,
      noise: 55,
    },
    infrastructure: {
      integrity: 99.7,
      vibrations: t('analysis.vibrations_low'),
      maintenance: [t('analysis.maint_sl_1')],
      lifeSupport: t('analysis.status_nominal'),
    },
    events: [
        { id: 1, type: "warning", text: t('analysis.event_sl_1'), time: t('analysis.time_1m') },
        { id: 2, type: "info", text: t('analysis.event_sl_2'), time: t('analysis.time_8m') },
        { id: 3, type: "info", text: t('analysis.event_sl_3'), time: t('analysis.time_12m') },
    ],
    crew: {
      assigned: 4,
      status: t('dashboard.sector_active'),
      occupation: 75,
      comfort: 4.5,
    },
  },
  "residential": {
    name: t('analysis.sector_residential_name'),
    status: {
      label: t('analysis.status_nominal'),
      color: "text-green-400",
      bgColor: "bg-green-400/10",
    },
    activityLevel: 40,
    crewCondition: 95,
    energy: {
      consumption: 8,
      capacity: 10,
      internalSourcePct: 90,
      systemTemp: 40,
      thermalEfficiency: 99.5,
      alerts: [],
    },
    environment: {
      lighting: 250,
      emergencyLights: "OK",
      temperature: 22,
      airQuality: 99.9,
      co2: 380,
      noise: 30,
    },
    infrastructure: {
      integrity: 99.9,
      vibrations: t('analysis.vibrations_none'),
      maintenance: [],
      lifeSupport: t('analysis.status_nominal'),
    },
    events: [
      { id: 1, type: "info", text: t('analysis.event_res_1'), time: t('analysis.time_2h') },
    ],
    crew: {
      assigned: 11,
      status: t('analysis.crew_status_rest'),
      occupation: 50,
      comfort: 4.9,
    },
  },
  "greenhouses": {
    name: t('analysis.sector_greenhouses_name'),
    status: {
      label: t('analysis.status_nominal'),
      color: "text-green-400",
      bgColor: "bg-green-400/10",
    },
    activityLevel: 75,
    crewCondition: 90,
    energy: {
      consumption: 15,
      capacity: 18,
      internalSourcePct: 85,
      systemTemp: 48,
      thermalEfficiency: 99.2,
      alerts: [],
    },
    environment: {
      lighting: 1000,
      emergencyLights: "OK",
      temperature: 24,
      airQuality: 99.7,
      co2: 600,
      noise: 45,
    },
    infrastructure: {
      integrity: 99.8,
      vibrations: t('analysis.vibrations_none'),
      maintenance: [],
      lifeSupport: t('analysis.status_nominal'),
    },
    events: [
        { id: 1, type: "system", text: t('analysis.event_gh_1'), time: t('analysis.time_30m') },
    ],
    crew: {
      assigned: 4,
      status: t('dashboard.sector_active'),
      occupation: 100,
      comfort: 4.7,
    },
  },
  "eclss": {
    name: t('analysis.sector_eclss_name'),
    status: {
      label: t('analysis.status_critical'),
      color: "text-red-400",
      bgColor: "bg-red-400/10",
    },
    activityLevel: 95,
    crewCondition: 85,
    energy: {
      consumption: 25,
      capacity: 25,
      internalSourcePct: 50,
      systemTemp: 65,
      thermalEfficiency: 97,
      alerts: [t('analysis.alert_eclss_1')],
    },
    environment: {
      lighting: 500,
      emergencyLights: "OK",
      temperature: 23,
      airQuality: 98,
      co2: 500,
      noise: 65,
    },
    infrastructure: {
      integrity: 99,
      vibrations: t('analysis.vibrations_high'),
      maintenance: [t('analysis.maint_eclss_1')],
      lifeSupport: t('analysis.ls_alert'),
    },
    events: [
        { id: 1, type: "warning", text: t('analysis.event_eclss_1'), time: t('analysis.time_5m') },
    ],
    crew: {
      assigned: 3,
      status: t('dashboard.sector_active'),
      occupation: 100,
      comfort: 3.5,
    },
  },
  "storage": {
    name: t('analysis.sector_storage_name'),
    status: {
      label: t('analysis.status_standby'),
      color: "text-yellow-400",
      bgColor: "bg-yellow-400/10",
    },
    activityLevel: 10,
    crewCondition: 98,
    energy: {
      consumption: 2,
      capacity: 5,
      internalSourcePct: 100,
      systemTemp: 35,
      thermalEfficiency: 99.8,
      alerts: [],
    },
    environment: {
      lighting: 100,
      emergencyLights: "OK",
      temperature: 18,
      airQuality: 99.9,
      co2: 400,
      noise: 25,
    },
    infrastructure: {
      integrity: 100,
      vibrations: t('analysis.vibrations_none'),
      maintenance: [],
      lifeSupport: t('analysis.status_nominal'),
    },
    events: [
        { id: 1, type: "info", text: t('analysis.event_stor_1'), time: t('analysis.time_8h') },
    ],
    crew: {
      assigned: 2,
      status: t('analysis.crew_status_rest'),
      occupation: 10,
      comfort: 4.6,
    },
  },
});

    